
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Dec 30 02:46:37 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NOTIDENTICAL = 26;
  public static final int IDENTICAL = 25;
  public static final int INCREMENT = 30;
  public static final int CONST = 14;
  public static final int CONSTBOOL = 36;
  public static final int LPAREN = 6;
  public static final int GREATER = 20;
  public static final int SEMI = 5;
  public static final int LESS = 18;
  public static final int MINUS = 17;
  public static final int DECREMENT = 31;
  public static final int RPAREN = 7;
  public static final int LESSEQUAL = 19;
  public static final int COMMA = 11;
  public static final int DIV = 23;
  public static final int PLUS = 10;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 8;
  public static final int NEW = 29;
  public static final int error = 1;
  public static final int MUL = 22;
  public static final int NUMBER = 33;
  public static final int MOD = 24;
  public static final int IDENT = 34;
  public static final int VOID = 13;
  public static final int GREATEREQUAL = 21;
  public static final int COLON = 28;
  public static final int LBRACE = 3;
  public static final int LSQUARE = 15;
  public static final int READ = 27;
  public static final int RSQUARE = 16;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int QUESTION = 32;
  public static final int CONSTCHAR = 35;
  public static final int PRINT = 12;
}

