
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Dec 16 15:06:53 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NOTIDENTICAL = 28;
  public static final int IDENTICAL = 27;
  public static final int CONST = 14;
  public static final int CONSTBOOL = 44;
  public static final int CASE = 38;
  public static final int LPAREN = 6;
  public static final int GREATER = 22;
  public static final int SEMI = 5;
  public static final int CONTINUE = 34;
  public static final int LESS = 20;
  public static final int MINUS = 19;
  public static final int RPAREN = 7;
  public static final int LESSEQUAL = 21;
  public static final int COMMA = 11;
  public static final int CLASS = 29;
  public static final int DIV = 25;
  public static final int PLUS = 10;
  public static final int IF = 17;
  public static final int DOT = 36;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 8;
  public static final int NEW = 40;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int NUMBER = 41;
  public static final int MOD = 26;
  public static final int IDENT = 42;
  public static final int BREAK = 33;
  public static final int VOID = 13;
  public static final int SWITCH = 37;
  public static final int GREATEREQUAL = 23;
  public static final int COLON = 39;
  public static final int LBRACE = 3;
  public static final int ELSE = 18;
  public static final int LSQUARE = 15;
  public static final int READ = 35;
  public static final int RSQUARE = 16;
  public static final int WHILE = 32;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 30;
  public static final int PROG = 2;
  public static final int CONSTCHAR = 43;
  public static final int PRINT = 12;
  public static final int DO = 31;
}

